# Generated by Django 4.2 on 2023-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('desarrollo', models.CharField(max_length=20)),
                ('dispositivo', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
