# Generated by Django 4.2 on 2023-06-04 18:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_juego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
